# Generated by Django 3.1.7 on 2021-07-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='test',
            new_name='text',
        ),
    ]
